config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :messages, only: [:new, :create]
  resources :videos, only: [:index, :new, :create]
  resources :projects
  
  get 'home/index'

  resources :cashflows

  resources :donaturs

  devise_for :users , :skip => :registrations
  resources :listings, only:[:legalitas, :struktur, :beranda, :tabel, :new, :create, :index, :edit, :update]
  get 'beranda' => 'listings#beranda'
  get 'tabel' => 'listings#tabel'
  
  resources :recipients do
    resources :cards
  end
    
  
  resources :years do
      resources :months
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
      member  do
        post :mark_as_read
      end
  end
  
  root 'listings#beranda'

end

app/models/recipient.rb
# == Schema Information
#
# Table name: recipients
#
#  id             :integer          not null, primary key
#  name           :string
#  nik            :string
#  born_place     :string
#  born_date      :string
#  gender         :string
#  blood_type     :string
#  address        :string
#  rukun_tetangga :string
#  rukun_warga    :string
#  kelurahan      :string
#  kecamatan      :string
#  city           :string
#  religion       :string
#  marital_status :string
#  job            :string
#  nationality    :string
#  pos_code       :string
#  province       :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  slug           :string
#

class Recipient < ActiveRecord::Base
  validates_format_of :name, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  extend FriendlyId
  has_many :cards, dependent: :destroy
  accepts_nested_attributes_for :cards, allow_destroy: true
  before_create :assign_month
  friendly_id :name, use: :slugged
  def should_generate_new_friendly_id?
    name_changed? || super
  end
  
  def assign_month
    array = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November','Desember']
    array.each do |a|
      cards.build(month: a, :recipient_id => :id)
    end
  end
  
  def alamat_lengkap
    "#{address}, RT #{rukun_tetangga}/RW #{rukun_warga}, Kelurahan #{kelurahan}, Kecamatan #{kecamatan}, #{province}, #{pos_code}"
  end
  
  def lahir
    "#{born_place}, #{born_date}"
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  layout "dashboard"  
  #before_action :authenticate_user!, except: [:index, :show, :santunan]
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]
  
  def santunan
    @recipients = Recipient.order('created_at asc')
    @cards = Card.all
  end
  
  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.order('created_at asc')
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
    @card = @recipient.cards.order('created_at asc')
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
    @card = @recipient.cards.build
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to recipients_path, notice: 'Recipient was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to recipients_path, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:name, :nik, :born_place, :born_date, :gender, :blood_type, :address, 
      :rukun_tetangga, :rukun_warga, :kelurahan, :kecamatan, :city, :religion, :marital_status, :job, :nationality, :pos_code, :province,
      :cards_attributes => [:recipient_id, :id, :employee, :amount, :month, :urut, :date])
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-md-8">
      <%= form_for(@recipient, :html => { class:"form-horizontal", role:"form"}) do |f| %>
        <% if @recipient.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@recipient.errors.count, "error") %></h2>

            <ul>
            <% @recipient.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="form-group">
          <%= f.label :name, "Nama", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :name, class: "form-control weight", id:"inputText3", placeholder:"input nama" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :nik, "No KTP", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :nik, class: "form-control weight", id:"inputText3", placeholder:"input no ktp" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :born_place, "Tempat Lahir", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :born_place, class: "form-control weight", id:"inputText3", placeholder:"input tempat lahir" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :born_date, "Tanggal Lahir", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :born_date, class: "datepicker form-control weight", id:"inputText3", placeholder:"input tanggal lahir" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :gender, "Jenis Kelamin", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %>
          <div class="col-sm-8 col-md-4">
            <%= f.select :gender, ['Laki - laki', 'Perempuan'],{prompt:"input jenis kelamin"},class: "form-control weight", id:"inputText3" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :blood_type, "Golongan Darah", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %>
          <div class="col-sm-8 col-md-4">
            <%= f.select :blood_type, ['A', 'B', 'AB', '0'],{prompt:"input jenis golongan darah"},class: "form-control weight", id:"inputText3" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :address, "Alamat", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :address, class: "form-control weight", id:"inputText3", placeholder:"input alamat" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :rukun_tetangga, "Rukun Tetangga", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :rukun_tetangga, class: "form-control weight", id:"inputText3", placeholder:"input rukun tetangga" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :rukun_warga, "Rukun Warga", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :rukun_warga, class: "form-control weight", id:"inputText3", placeholder:"input rukun warga" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :kelurahan, "Kelurahan", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :kelurahan, class: "form-control weight", id:"inputText3", placeholder:"input rukun kelurahan" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :kecamatan, "Kecamatan", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :kecamatan, class: "form-control weight", id:"inputText3", placeholder:"input kecamatan" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :city, "Kota", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :city, class: "form-control weight", id:"inputText3", placeholder:"input kota" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :religion, "Agama", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :religion, class: "form-control weight", id:"inputText3", placeholder:"input agama" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :marital_status, "Status Perkawinan", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %>
          <div class="col-sm-8 col-md-4">
            <%= f.select :marital_status, ['Kawin', 'Belum Kawin','Cerai Hidup', 'Cerai Mati'],{prompt:"input jenis kelamin"},class: "form-control weight", id:"inputText3" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :job, "Pekerjaan", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :job, class: "form-control weight", id:"inputText3", placeholder:"input pekerjaan" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :pos_code, "Kode Pos", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :pos_code, class: "form-control weight", id:"inputText3", placeholder:"input kodepos" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :province, "Provinsi", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :province, class: "form-control weight", id:"inputText3", placeholder:"input propinsi" %>
          </div>
        </div>
      
        <div class="form-group">
          <%= f.label :nationality, "Negara", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight"  %>
          <div class="col-sm-8 col-md-4">
            <%= f.text_field :nationality, class: "form-control weight", id:"inputText3", placeholder:"input negara" %>
          </div>
        </div>
           
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-3 col-md-offset-3">
             <%= action_name == "new" ? (f.submit "Buat Santunan", class:"btn btn-success"):(f.submit "Edit Santunan", class:"btn btn-success") %>
          </div>
        </div>
      
        <br>
        <% end %>
    </div>
  </div>
</div>

app/views/recipients/edit.html.erb
<div class="col-sm-8 col-md-8">
  <h3 class="lead">Buat Santunan</h3>
</div>

<%= render 'form' %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-md-8">
      <%= link_to 'Lihat', @recipient %> |
      <%= link_to 'Kembali', recipients_path %>
    </div>
  </div>
</div>

app/views/recipients/index.html.erb
<div class="container-fluid" id="recipients">
  <div class="row">
    <div class="col-md-12">
      <% unless @recipients.blank? %>
      <h4>Penerima Santunan Bulanan</h4>

      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Nama</th>
            <th>Tempat, Tanggal Lahir</th>
            <th class="hidden-xs hidden-sm">Alamat</th>
            <th>Pekerjaan</th>
            <% if signed_in? %>
            <th colspan="2"></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @recipients.each do |recipient| %>
            <tr>
              <td><%= link_to recipient.name, recipient %></td>
              <td><%= recipient.lahir %></td>
              <td class="hidden-xs hidden-sm"><%= recipient.alamat_lengkap %></td>
              <td><%= recipient.job %></td>
              <% if signed_in? %>
              <td><%= link_to '<span class="glyphicon glyphicon-edit" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></span>'.html_safe, edit_recipient_path(recipient) %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Hapus"></span>'.html_safe, recipient, method: :delete, data: { confirm: 'Anda Yakin Hapus?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <div class="col-md-12 col-sm-12 col-xs-12"><h1 class="center">Maaf Belum Ada Data Yang Bisa Diperlihatkan</h1></div>
      <% end %>

      <br>
      <%# if signed_in? %>
      <%= link_to 'Tambah Santunan', new_recipient_path %>
      <%# end %>
      
    </div>
  </div>
</div>

app/views/recipients/new.html.erb
<div class="col-sm-8 col-md-8">
  <h3 class="lead">Buat Santunan</h3>
</div>

<%= render 'form' %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-md-8">
      <%= link_to 'Kembali', recipients_path %>
    </div>
  </div>
</div>

app/views/recipients/santunan.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <% unless @recipients.blank? %>
      <h4>Penerima Santunan Bulanan</h4>

      <table class="table table-hover table-striped table-condensed">
        <thead>
          <tr>
            <th>Nama</th>
            <th>Tempat, Tanggal Lahir</th>
            <th class="hidden-xs hidden-sm">Alamat</th>
            <th>Pekerjaan</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @recipients.each do |recipient| %>
            <tr>
              <td><%= link_to recipient.name, recipient %></td>
              <td><%= recipient.lahir %></td>
              <td class="hidden-xs hidden-sm"><%= recipient.alamat_lengkap %></td>
              <td><%= recipient.job %></td>
              <% if signed_in? %>
              <td><%= link_to '<span class="glyphicon glyphicon-edit" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></span>'.html_safe, edit_recipient_path(recipient) %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Hapus"></span>'.html_safe, recipient, method: :delete, data: { confirm: 'Anda Yakin Hapus?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>

      <br>
      <%# if signed_in? %>
      <%= link_to 'Tambah Santunan', new_recipient_path %>
      <%# end %>
      
    </div>
  </div>
</div>

app/views/recipients/show.html.erb
<div class="container-fluid">
  <div class="row">
    </div><div class="col-xs-12 col-sm-4 col-md-4">
      <div class="panel panel-success">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
  
        <!-- Table -->
        <table class="table table-hover">
    
          <tbody>  
          
              <tr>
                <td>Nama</td>
                <td><%= @recipient.name %></td>
              </tr>
          
              <tr>
                <td>Nomor KTP</td>
                <td><%= @recipient.nik %></td>
              </tr>
              <tr>
                <td>Tempat, Tanggal Lahir</td>
                <td><%= @recipient.lahir %></td>
              </tr>
              <tr>
                <td>Alamat Lengkap</td>
                <td><%= @recipient.alamat_lengkap %></td>
              </tr>
              <tr>
                <td>Agama</td>
                <td><%= @recipient.religion %></td>
              </tr>
              <tr>
                <td>Status</td>
                <td><%= @recipient.marital_status %></td>
              </tr>
              <tr>
                <td>Kode Pos</td>
                <td><%= @recipient.pos_code %></td>
              </tr>
              <tr>
                <td>Propinsi</td>
                <td><%= @recipient.province %></td>
              </tr>
              <tr>
                <td>Negara</td>
                <td><%= @recipient.nationality %></td>
              </tr>
          
          
          </tbody>
        </table>
  
        <div class="panel-footer">
          <%# if signed_in? %>
              <%#= link_to 'Edit', edit_recipient_path(@recipient), class:"btn btn-default" %> 
          <%# end %>
          <%#= link_to 'Kembali', santunan_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>


    <div class="col-xs-12 col-sm-4 col-md-4">
      <div class="panel panel-success">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
  
        <!-- Table -->
        <table class="table table-hover table-bordered">
          <tbody>  
              <tr>
                <td class="warnatabel center">No</td>
                <td class="warnatabel">Bulan</td>
                <td class="warnatabel">Tanggal</td>
                <td class="warnatabel center">Jumlah</td>
                <td class="warnatabel">Petugas</td>
                <% if signed_in? %>
                <td class="warnatabel center" colspan="2"></td>
                <% end %>
              </tr>
                <% @card.each_with_index do |card, i| %>
              <tr>
                <td class="center"><%= i = i + 1 %></td>
                <td><%= card.month %></td>
                <td><%= card.date %></td>
                <td><%= "#{number_to_currency(card.amount, precision: 0, unit: "Rp ")}" %></td>
                <td><%= card.employee %></td>
                <%# if signed_in? %>
                <% if card.amount || card.employee || card.date  %>
                <td><%= link_to 'Edit', edit_recipient_card_path(@recipient, card)  %></td>
                <% else %>
                <td><%= link_to 'Isi', edit_recipient_card_path(@recipient, card)  %></td>
                <% end %>
                <%# end %>
              </tr> 
            <% end %>
          </tbody>
        </table>
  
        <div class="panel-footer">
          <%#= link_to 'Buat Bukti Penyaluran', edit_recipient_card_path(@recipient, @card) %>
          <%# if signed_in? %>
          <%#= unless @cards.blank? %>
              <%#= link_to 'Edit', edit_recipient_card_path(@recipient), class:"btn btn-default" %> 
          <%# end %>
          <%#= link_to 'Kembali', santunan_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <%= link_to 'Kembali', recipients_path %>
    </div>
  </div>
</div>