config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :messages, only: [:new, :create]
  resources :videos, only: [:index, :new, :create]
  resources :projects
  
  get 'home/index'

  resources :cashflows

  resources :donaturs

  devise_for :users , :skip => :registrations
  resources :listings, only:[:legalitas, :struktur, :beranda, :tabel, :new, :create, :index, :edit, :update]
  get 'beranda' => 'listings#beranda'
  get 'tabel' => 'listings#tabel'
  
  resources :recipients do
    resources :cards
  end
    
  
  resources :years do
      resources :months
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
      member  do
        post :mark_as_read
      end
  end
  
  root 'listings#beranda'

end

app/models/donatur.rb
# == Schema Information
#
# Table name: donaturs
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Donatur < ActiveRecord::Base
  has_many :listings, dependent: :destroy
  accepts_nested_attributes_for :listings, allow_destroy: true
  before_create :set_list
  # before_action :set_list
  extend FriendlyId
  friendly_id :name, use: :slugged
  def should_generate_new_friendly_id?
    name_changed? || super
  end
  
  def set_list
    Year.all.each do |year|
      year.months.each do |month|
        listings.build(:month => month, :year => year)
      end
    end
  end
  
end

app/controllers/donaturs_controller.rb
class DonatursController < ApplicationController
  layout "dashboard"
  #before_action :authenticate_user!, except: [:index, :show]
  before_action :set_donatur, only: [:show, :edit, :update, :destroy]

  # GET /donaturs
  # GET /donaturs.json
  def index
    @donaturs = Donatur.order('created_at asc')
  end

  # GET /donaturs/1
  # GET /donaturs/1.json
  def show
  end

  # GET /donaturs/new
  def new
    @donatur = Donatur.new
  end

  # GET /donaturs/1/edit
  def edit
  end

  # POST /donaturs
  # POST /donaturs.json
  def create
    @donatur = Donatur.new(donatur_params)

    respond_to do |format|
      if @donatur.save
        format.html { redirect_to donaturs_path, notice: 'Donatur was successfully created.' }
        format.json { render :show, status: :created, location: @donatur }
      else
        format.html { render :new }
        format.json { render json: @donatur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donaturs/1
  # PATCH/PUT /donaturs/1.json
  def update
    respond_to do |format|
      if @donatur.update(donatur_params)
        format.html { redirect_to donaturs_path, notice: 'Donatur was successfully updated.' }
        format.json { render :show, status: :ok, location: @donatur }
      else
        format.html { render :edit }
        format.json { render json: @donatur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donaturs/1
  # DELETE /donaturs/1.json
  def destroy
    @donatur.destroy
    respond_to do |format|
      format.html { redirect_to donaturs_url, notice: 'Donatur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donatur
      @donatur = Donatur.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donatur_params
      params.require(:donatur).permit(:name)
    end
end

app/helpers/donaturs_helper.rb
module DonatursHelper
end

app/views/donaturs/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-md-8">
  <%= form_for(@donatur, :html => { class:"form-horizontal", role:"form"}) do |f| %>
    <% if @donatur.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@donatur.errors.count, "error") %> prohibited this donatur from being saved:</h2>

        <ul>
        <% @donatur.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, "Nama", for: "inputText3", class:"col-sm-3 col-md-3 control-label weight" %><br>
      <div class="col-sm-8 col-md-4"><%= f.text_field :name, class:"form-control weight", id:"inputText3", placeholder:"input nama" %></div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-3 col-md-offset-3">
         <%= action_name == "new" ? (f.submit "Buat Tabel", class:"btn btn-success"):(f.submit "Edit Tabel", class:"btn btn-success") %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/donaturs/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">

      <%= render 'form' %>

      <%= link_to 'Show', @donatur %> |
      <%= link_to 'Back', donaturs_path %>
      
    </div>
  </div>
</div>

app/views/donaturs/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12" id="donaturs">
      <% unless @donaturs.blank? %>
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <td><h3>Donatur</h3></td>
            <% if signed_in? %>
            <td colspan="2"></td>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @donaturs.each do |donatur| %>
            <tr>
              <td><%= link_to donatur.name, donatur %></td>
              <% if signed_in? %>
              <td><%= link_to '<span class="glyphicon glyphicon-edit" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Edit"></span>'.html_safe, edit_donatur_path(donatur) %></td>
              <td><%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden="true"data-toggle="tooltip" data-placement="top" title="Hapus"></span>'.html_safe,  donatur, method: :delete, data: { confirm: 'Anda Yakin Hapus?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
      <br>
      <%# if signed_in? %>
      <%= link_to 'Tambah Donatur', new_donatur_path %>
      <%# end %>
    </div>
  </div>
</div>

app/views/donaturs/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form' %>

      <%= link_to 'Back', donaturs_path %>
      
    </div>
  </div>
</div>

app/views/donaturs/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-md-4" id="donaturs">
      <div class="panel panel-success">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
  
        <!-- Table -->
        <table class="table table-hover">  
          <tbody>  
              <tr>
                <td>Nama</td>
                <td><%= @donatur.name.camelize %></td>
              </tr>
          </tbody>
        </table>
  
        <div class="panel-footer">
          <% if signed_in? %>
              <%= link_to 'Edit', edit_donatur_path(@donatur), class:"btn btn-default" %> 
          <% end %>
          <%= link_to 'Kembali', donaturs_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>